### ISSUE TITLE
우리가 이 wikilite 를 쏙에서 사용하기위해서 꼭 필요한 기능에는 뭐가 있을가요?

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#12]
우리가 이 wikilite 를 쏙에서 사용하기위해서 꼭 필요한 기능에는 뭐가 있을가요?

가장 필요한 기능에 대한 의견을 제시해 주시면, 종합해서 어떻게 설계를 할지 구상해 보면

좋을거 같네요.

**Comment by becxer** [comment]
저같은 경우엔 2가지 의견이 있는데요.
1) TODO 리스트는 꼭 필요한것 같다 ( 우리 끼리 뭐해야 할지 모르는경우가 종종 있으므로 )
2) 분산되어있는 구글드라이브, 메일링 리스트를 접근성 좋게 해결하면 좋겠다!

**Comment by becxer** [comment]
알고리즘 스터디때 공부했던 자료를 위키라이트에 정리 해보자는 의견도 있었음!

**Comment by StaySharp0** [comment]
그거 괜찮네요.
