### ISSUE TITLE
폴더별로 프로젝트 탭으로 볼수있도록 하기

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#2]
네비게이션 바 형태면 좋을것 같기도?

이곳 참조 . http://hp100.net/wikilite/index.php

**Comment by StaySharp0** [comment]
진행하고 있습니다. 2시 안에 작성하도록 노력해볼께요

**Comment by becxer** [comment]
오 역시 용준님 빠르시군요! 꼭 새로 git pull 해서 작성해주시길바래요! README랑 설치법이랑 이것저것 고쳐서..

**Comment by StaySharp0** [comment]
버전업하고 README 수정했는데 설치법 이따가 고쳐볼께요.

**Comment by becxer** [comment]
넵 좋아요
