### ISSUE TITLE
설정 할만한 요소들은 config 란 파일로 관리 하는게 어떨까요?

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#24]
keys도 위치가 루트라 지금 좀 애매한듯

**Comment by StaySharp0** [comment]
key파일 위치랑
project 지정할수 있게하고
github 저장소 자동으로 클론할수 잇도록 하는것도 괜찮을꺼같아요.

**Comment by becxer** [comment]
넹 좋은 아이디어 네요
