### ISSUE TITLE
위키내 연결을 걸수있도록 피드별 페이지화

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#3]
예를들면, 특정 md 파일이 특정 url과 연결되도록.
아래 예시 참조.
http://hp100.net/wikilite/index.php/engine/project/people-lang

**Comment by StaySharp0** [comment]
구현은 했으나 한글이름을 가진 md파일의 경우  url이 깨지는 문제가 있네요.

**Comment by StaySharp0** [comment]
해결했습니다.
