### ISSUE TITLE
category 나 filter 를 없애면 ( 콘솔상으로) 업데이트가 안됨.

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#32]
이 문제는 초기에만 로딩하는것 때문에 문제가 되는듯. 추후에 del 기능 구현시
폴더 로딩을 다시해주어야 함.

**Comment by StaySharp0** [comment]
reset이라는 라우팅함수로 초기화 할수 있는데 시점을 조정하지 못했습니다.
