### ISSUE TITLE
디렉토리별 뉴스피드화 다시 구현하기

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#4]
디렉토리별 뉴스피드화 다시 구현하기
아래 링크를 참조하면, 디렉토리별로 md파일들이 마치 페이스북의 뉴스피드처럼 리스트 되있는것을 볼수있다. 이 기능을 다시 구현해야 한다. 혹은, 더 좋은 아이디어가 있다면 바꾸어도 좋겠다.

http://hp100.net/wikilite/index.php

**Comment by StaySharp0** [comment]
구현 완료.
트렐로의 형태를 가지는 것도 좋을 꺼같아요.
