### ISSUE TITLE
md파일 구조 설계 

### ISSUE THREAD

**Issue by StaySharp0** [becxer/wikilite#5]
디렉토리및 md 파일을 어떤 구조로 만들건지 고민좀 해봐야 할꺼 같네요.

**Comment by becxer** [comment]
우리가 탭에는 어떤 정보들이 들어가고 메인바디에 어떤 정보가 들어가느냐에 따라서 달라질것 같긴한데, 일단 저의 생각은 탭은 개별 프로젝트(예를들면 웹스터디 탭이 있는거) 로 보고 그안에 문서나 세부 디렉토리가 들어있는 형태면 어떨까합니다만 ㅋㅋ 이렇게 했을때의 장점으로는 만약 슬랙의 채널을 프로젝트별로 생성했을때 연동하기가 깔끔하다는 점이 있을것 같습니다. 혹시 좋은 의견이 있으신지! ?

**Comment by StaySharp0** [comment]
아직까지는 좋은 의견은 없습니다. 일단 파일 시스템 구조 관련해서 다른 자료들 찾아보며 참고 할 계획입니다. :)

**Comment by mjh410** [comment]
1. 폴더 안에 폴더는 무엇을 뜻할 것인지
2. 폴더 안에 폴더의 경로 설정
3. Document 로 사용자에게 제공할 형식

**Comment by mjh410** [comment]
1. 폴더안의 폴더 - 방법1
2. conference  > #회 (폴더) > #회의 정보 (.md)
3. study  > 스터디명 (폴더) > 해당 스터디의 정보 (.md)
   이런식으로 하는것

**Comment by mjh410** [comment]
폴더안에 폴더 - 나타내는법
side menu
conference 에 마우스 커서를 갖다 대었을때 #회 목록 리스트가 보인다.
(ex) http://navercast.naver.com/magazine_index.nhn (이미지는 모두 글로 보시면 됩니다)

> > 매 회의 내부에는 연사님들을 발표한 순서로 소개되어있고 행사 소개가 있다
