### ISSUE TITLE
TODO: md파일 한글이름 url 문제 해결

### ISSUE THREAD

**Issue by oh4851** [becxer/wikilite#7]
commit hash: 3c5a73d8baee89907cd1e1d563b244868b416a52

한글이름.md 일경우 -> 한글깨짐 문제
-> 한글이름.md부분 제외한 url전달 -> 한글이름.md file io -> concat -> send

TODO:
char encoding to utf-8

**Comment by StaySharp0** [comment]
md파일별 url이 페이지 접속했을 때 보이는 문제인데요. 제가 설명을 잘못했네요. ㅜ

**Comment by becxer** [comment]
오토디플로이
