### ISSUE TITLE
제가 처음 위키라이트를 시작하면서 생각했었던 아이디어들

### ISSUE THREAD

**Issue by becxer** [becxer/wikilite#8]
폴더별로 프로젝트 탭으로 볼수있도록 하기

페이지 별로 피드를 볼수있도록 만들기? (옵션 탭이 있으면 좋을것 같다)

그림을 표현할 수가 없잖아 매우 불편하네 빨리 만들자

온라인 상에서 수정할 수 있도록 만들기

액션플랜은 앞으로 작성할 문서의 링크여도 좋을것 같다.

파일제목은 (글번호-연월날짜-제목.md)로 하기로 한다. 

만약 사용자가 설정하지 않았으면, 자동으로 

제목설정(히스토리관리)

페이지 이동없이 위키링크를 클릭하면, 아래에 피드가 

생기는 방식의 트래킹피드로 만들자

피드의 오른편 위 x표시를 누르면 피드가 꺼질수 있도록

시간나면, 단축키도 좀 만들고.

로그인으로 비밀글 쓰기기능도 좋을것 같다

자동으로 엔진을 업데이트 할수있는 스크립트 만들기.

댓글기능.

위키내 연결을 걸수있도록 피드별 페이지화

**Comment by becxer** [comment]
반드시 이렇게 해야하진 않고,

우리가 목표로 하는 " Todo 리스트와 Wiki 가 결합된 " 것을 기억하며,
화려한 기능보다 우선 우리가 쓸만한 프로젝트로 만드는데 집중하면 좋을것 같습니다.

한가지 새로운 아이디어는, 히스토리 관리 같은경우 project 폴더 만 git과 연동하거나 
혹은 구글 드라이브와 연동해서 구현하지 않고 가져가는 방법도 고려해볼만 하다고 생각됩니다.
(그리고 . 추후에 gitignore 에 projects 폴더를 추가하여 우리 회의록이 github에 공유되지 않을 필요가 있습니다)

**Comment by StaySharp0** [comment]
제 고민은 노트 추가기능이 생겼을때 파일과 디렉토리의 구조를 어떻게 구성해서 체계화가 되야할지 고민입니다.

**Comment by mjh410** [comment]
확장성을 위해 폴더를 계속 타고 들어가도 json방식 으로 저장해주는 것을 구현하다가 막혀서 주석처리를 해두었습니다. 
참고사이트 : http://huskdoll.tistory.com/11
http://msdn.microsoft.com/ko-kr/library/ie/cc836459(v=vs.94).aspx
왜 안되는지 모르겠음 내생각에는 용준이가 return; 을 좀 쎄게 밟은것 같음
